# SQS constants
LOCAL_SQS_URL = 'https://sqs.us-east-1.amazonaws.com/014498654370/local-queue.fifo'
HTTP_200_STATUS = 200
SQS_RECEIVED_KEYWORD = 'RECEIVED'
SQS_PROCESSED_AND_DELETED_KEYWORD = "PROCESSED -> DELETED"

SQS_RETRY_INTERVAL = 30  # seconds
